# Generated by Django 4.2 on 2023-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_first_name', models.CharField(max_length=100, verbose_name='Doctor First Name:')),
                ('d_last_name', models.CharField(max_length=100, verbose_name='Doctor Last Name:')),
                ('d_age', models.IntegerField(verbose_name='Doctor Age:')),
                ('d_gender', models.CharField(max_length=100, verbose_name='Doctor Gender:')),
                ('d_phone_number', models.IntegerField(verbose_name='Doctor Phone Number:')),
                ('d_email_id', models.EmailField(max_length=100, verbose_name='Doctor EmailId:')),
                ('d_address', models.TextField(verbose_name=200)),
                ('d_department', models.CharField(blank=True, choices=[('General CheckUp', 'General CheckUp'), ('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Psychiatry', 'Psychiatry'), ('Neuro Surgery', 'Neuro Surgery'), ('Orthopaedics', 'Orthopaedics')], default='General CheckUp', max_length=100)),
            ],
            options={
                'ordering': ['d_last_name', 'd_first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_first_name', models.CharField(max_length=50, verbose_name='Patient First Name:')),
                ('p_last_name', models.CharField(max_length=50, verbose_name='Patient last Name:')),
                ('p_age', models.IntegerField(verbose_name='Patient Age:')),
                ('p_gender', models.CharField(max_length=20, verbose_name='Patient Gender:')),
                ('p_phone_number', models.IntegerField(verbose_name='Patient Phone Number:')),
                ('p_email_id', models.EmailField(max_length=100, verbose_name='Patient EmailId:')),
                ('p_department', models.CharField(max_length=100, verbose_name='Patient Health Department')),
                ('P_application_date', models.DateField(null=True, verbose_name='Patient Application Date:')),
                ('p_application_time', models.TimeField(null=True, verbose_name='Patient Application Time:')),
                ('p_health_problem', models.TextField(verbose_name='Brief Explanation of health problem:')),
            ],
            options={
                'ordering': ['p_last_name', 'p_first_name'],
            },
        ),
    ]
