# Generated by Django 4.2 on 2023-04-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='d_gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male'), ('N', 'none')], default='N', max_length=100, verbose_name='Doctor Gender:'),
        ),
    ]
