# Generated by Django 4.2 on 2023-04-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctordetails_d_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='d_address',
            field=models.TextField(verbose_name='Doctor Address'),
        ),
    ]
