# Generated by Django 4.2 on 2023-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctordetails_d_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='P_application_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='p_application_time',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='p_department',
            field=models.CharField(choices=[('General CheckUp', 'General CheckUp'), ('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Psychiatry', 'Psychiatry'), ('Neuro Surgery', 'Neuro Surgery'), ('Orthopaedics', 'Orthopaedics')], default='General CheckUp', max_length=100, verbose_name='Health Department'),
        ),
    ]
