# Generated by Django 4.2 on 2023-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_patientdetails_p_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='p_application_date_time',
            field=models.DateTimeField(null=True, verbose_name='Patient Application date and time:'),
        ),
    ]
